---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name:  kube-logrotate
spec: {}
status: {}
---
# Source: logrotate/templates/configMap.yaml
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    annotations:
      fabric8.io/target-platform: kubernetes
    labels:
      app: logrotate
      group: com.stakater.platform
      provider: stakater
      version: "3.13.0"
      chart: "logrotate-1.0.19"
      release: "ffn-logrotate"
      heritage: "Helm"
    name: logrotate
    namespace: kube-logrotate
  data:
    k8s-rotator.conf:  |-
      /var/lib/docker/containers/*/*.log {
        rotate 20
        copytruncate
        missingok
        notifempty
        compress
        maxsize 500M
        daily
      }
